---
- name: linux Install Java, nginx, python3, docker on linux-server
  hosts: linux-server
  vars:
    ansible_user: "adminuser"
    ansible_password: "P@ssw0rd123!"
  tasks:
    - name: Update APT package manager repositories cache
      become: true
      apt:
        update_cache: yes

    - name: Install Java
      become: yes
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - openjdk-17-jdk
          - nginx
          - python3
          - docker.io

    - name: Start NGINX
      service:
        name: nginx
        state: started
        enabled: yes          
...