---
- name: linux Install Apache2, Java, MySQL, nginx, python3, docker and npm on linux-server
  hosts: linux-server
  vars:
    ansible_user: "adminuser"
    ansible_password: "P@ssw0rd123!"
  tasks:
    - name: Update APT package manager repositories cache
      become: true
      apt:
        update_cache: yes

    - name: Install java, apache2, nginx
      become: yes
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - openjdk-17-jdk
          - apache2
          - nginx
...